const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
if(location.protocol==='file:') $('#fileWarning').classList.remove('hidden');
let config={}, terminalSocket=null, terminalConnected=false, testJob=null, manualLoaded=false, metricState={}, topologyEditing=false, selectedTopologyNode=null;
let terminalBuffer=$('#terminalOutput').textContent;
const titles={dashboard:['监控看板','实时掌握相机链路运行状态'],terminal:['命令终端','通过 SSH 执行远端指令并查看实时输出'],tests:['测试中心','配置化运行、观察和停止测试脚本'],settings:['平台配置','一个内核，适配不同芯片与项目'],manual:['用户手册','工具介绍、操作方法与平台配置参考']};
async function api(path,options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const d=await r.json();if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}
function toast(s){const e=$('#toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showPage(id){$$('.page,nav button').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$(`nav button[data-page="${id}"]`).classList.add('active');$('#pageTitle').textContent=titles[id][0];$('#subtitle').textContent=titles[id][1];if(id==='manual'&&!manualLoaded)loadManual();if(id==='terminal'){connectTerminal();setTimeout(()=>$('#terminalOutput').focus())}}
$$('nav button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
$('.connection-panel>p').textContent='支持私钥或密码认证。密码会明文写入被 Git 忽略的 target.local.json，请限制文件权限。';
$('#sshForm [name="password"]').placeholder='留空则使用私钥认证';
$('#sshForm [name="password"]+small').textContent='保存后写入 target.local.json；留空保存会清除已有密码';
function manualInline(text){return esc(text).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>')}
function renderManual(markdown){const lines=markdown.split(/\r?\n/),html=[];let code=[],inCode=false,list=null,headingIndex=0;const closeList=()=>{if(list){html.push(`</${list}>`);list=null}};for(const line of lines){if(line.startsWith('```')){if(inCode){html.push(`<pre><code>${esc(code.join('\n'))}</code></pre>`);code=[];inCode=false}else{closeList();inCode=true}continue}if(inCode){code.push(line);continue}const heading=line.match(/^(#{1,3})\s+(.+)$/);if(heading){closeList();const level=heading[1].length,id=`manual-heading-${headingIndex++}`;html.push(`<h${level} id="${id}">${manualInline(heading[2])}</h${level}>`);continue}const bullet=line.match(/^[-*]\s+(.+)$/),ordered=line.match(/^\d+\.\s+(.+)$/);if(bullet||ordered){const wanted=bullet?'ul':'ol';if(list!==wanted){closeList();list=wanted;html.push(`<${list}>`)}html.push(`<li>${manualInline((bullet||ordered)[1])}</li>`);continue}closeList();if(/^\|.*\|$/.test(line)&&!/^\|[-: |]+\|$/.test(line)){const cells=line.slice(1,-1).split('|').map(x=>`<span>${manualInline(x.trim())}</span>`).join('');html.push(`<div class="manual-table-row">${cells}</div>`)}else if(line.trim()){html.push(`<p>${manualInline(line)}</p>`)}}closeList();$('#manualContent').innerHTML=html.join('');const headings=[...$('#manualContent').querySelectorAll('h2')];$('#manualToc').innerHTML=headings.map(h=>`<a href="#${h.id}">${h.textContent}</a>`).join('')}
async function loadManual(){try{const data=await api('/api/manual');renderManual(data.content);manualLoaded=true}catch(e){$('#manualContent').innerHTML=`<p class="stderr">${esc(e.message)}</p>`}}
function topologyMetric(id){return id?metricState[id]:null}
function positiveState(metric,kind){if(!metric||metric.ok===false)return false;const value=String(metric.value).toUpperCase();const accepted=kind==='video'?['VIDEO LOCK','VIDEO_LOCK','STREAMING','LOCKED','ONLINE','1','0X1']:['LINK LOCK','LINK_LOCK','LOCKED','ONLINE','1','0X1'];return accepted.includes(value)}
function edgeState(edge){const link=topologyMetric(edge.linkMetric),video=topologyMetric(edge.videoMetric);if(!link)return'unknown';if(!positiveState(link,'link'))return'lost';return positiveState(video,'video')?'video':'linked'}
function renderTopology(){const topology=config.topology;if(!topology||!Array.isArray(topology.nodes)||!topology.nodes.length){$('#topology').innerHTML='<div class="topology-empty">当前平台未配置拓扑图</div>';return}const nodes=Object.fromEntries(topology.nodes.map(n=>[n.id,n])),edges=topology.edges||[],nodeStates={};const edgeMarkup=edges.map(edge=>{const a=nodes[edge.from],b=nodes[edge.to];if(!a||!b)return'';const state=edgeState(edge);(nodeStates[a.id]??=[]).push(state);(nodeStates[b.id]??=[]).push(state);const x1=Number(a.x),y1=Number(a.y),x2=Number(b.x),y2=Number(b.y),mx=(x1+x2)/2,my=(y1+y2)/2,label=state==='video'?'VIDEO LOCK':state==='linked'?'LINK LOCK':state==='lost'?'LINK LOST':'WAITING';return `<g class="topology-edge ${state}"><path d="M ${x1} ${y1} L ${x2} ${y2}"/>${state==='video'?`<path class="data-flow" d="M ${x1} ${y1} L ${x2} ${y2}"/>`:''}${state==='lost'?`<g class="break-mark" transform="translate(${mx} ${my})"><circle r="3.3"/><path d="M-1.3-1.3L1.3 1.3M1.3-1.3L-1.3 1.3"/></g>`:''}<text x="${mx}" y="${my-2.7}">${label}</text></g>`}).join('');const nodeMarkup=topology.nodes.map(node=>{const x=Math.max(0,Math.min(100,Number(node.x))),y=Math.max(0,Math.min(100,Number(node.y))),states=nodeStates[node.id]||[],hasGood=states.includes('video')||states.includes('linked');const state=states.includes('lost')&&hasGood?'degraded':states.includes('video')?'video':states.includes('linked')?'linked':states.includes('lost')?'lost':'unknown';const status={video:'STREAMING',linked:'LINKED',lost:'LOST',degraded:'DEGRADED',unknown:'UNKNOWN'}[state];return `<div data-node-id="${esc(node.id)}" class="topology-node ${esc(node.type||'device')} ${state} ${topologyEditing&&selectedTopologyNode===node.id?'selected':''}" style="left:${x}%;top:${y}%"><span>${esc(node.label||node.id)}</span>${node.subtitle?`<small>${esc(node.subtitle)}</small>`:''}<b>${status}</b></div>`}).join('');$('#topology').innerHTML=`<svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Camera connection topology">${edgeMarkup}</svg>${nodeMarkup}`;if(topologyEditing)bindTopologyDrag()}
function topologyNode(id=selectedTopologyNode){return config.topology?.nodes?.find(n=>n.id===id)}
function bindTopologyDrag(){$$('#topology .topology-node').forEach(element=>{element.onpointerdown=event=>{event.preventDefault();selectedTopologyNode=element.dataset.nodeId;refreshTopologyEditor();renderTopology();const active=$$('#topology .topology-node').find(n=>n.dataset.nodeId===selectedTopologyNode),node=topologyNode(),box=$('#topology').getBoundingClientRect();const move=e=>{node.x=Math.max(3,Math.min(97,Math.round((e.clientX-box.left)/box.width*100)));node.y=Math.max(4,Math.min(96,Math.round((e.clientY-box.top)/box.height*100)));active.style.left=node.x+'%';active.style.top=node.y+'%';$('#topologyNodeX').value=node.x;$('#topologyNodeY').value=node.y};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);renderTopology()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}})}
function topologyOptions(items,selected='',empty=''){return `${empty?`<option value="">${esc(empty)}</option>`:''}${items.map(item=>`<option value="${esc(item.id)}" ${item.id===selected?'selected':''}>${esc(item.label||item.name||item.id)}</option>`).join('')}`}
function refreshTopologyEditor(){const topology=config.topology||(config.topology={nodes:[],edges:[]}),nodes=topology.nodes,metrics=config.monitoring?.metrics||[];if(selectedTopologyNode&&!topologyNode())selectedTopologyNode=null;if(!selectedTopologyNode&&nodes.length)selectedTopologyNode=nodes[0].id;$('#topologyNodeSelect').innerHTML=topologyOptions(nodes,selectedTopologyNode);const node=topologyNode();for(const [id,value] of [['topologyNodeLabel',node?.label||''],['topologyNodeSubtitle',node?.subtitle||''],['topologyNodeX',node?.x??''],['topologyNodeY',node?.y??'']])$('#'+id).value=value;$('#topologyNodeType').value=node?.type||'device';const nodeOpts=topologyOptions(nodes);$('#edgeFrom').innerHTML=nodeOpts;$('#edgeTo').innerHTML=nodeOpts;const metricOpts=topologyOptions(metrics,'','不绑定');$('#edgeLinkMetric').innerHTML=metricOpts;$('#edgeVideoMetric').innerHTML=metricOpts;$('#topologyEdgeList').innerHTML=(topology.edges||[]).map((edge,index)=>`<div class="edge-item"><span>${esc(edge.from)} → ${esc(edge.to)}<small>Link: ${esc(edge.linkMetric||'--')} · Video: ${esc(edge.videoMetric||'--')}</small></span><button data-edge-index="${index}">删除</button></div>`).join('')||'<span class="no-params">暂无连接</span>';$$('#topologyEdgeList button').forEach(button=>button.onclick=()=>{topology.edges.splice(Number(button.dataset.edgeIndex),1);refreshTopologyEditor();renderTopology()})}
function updateTopologyNode(){const node=topologyNode();if(!node)return;node.label=$('#topologyNodeLabel').value.trim()||node.id;node.subtitle=$('#topologyNodeSubtitle').value.trim();node.type=$('#topologyNodeType').value;node.x=Math.max(0,Math.min(100,Number($('#topologyNodeX').value)||0));node.y=Math.max(0,Math.min(100,Number($('#topologyNodeY').value)||0));renderTopology();refreshTopologyEditor()}
function renderMetrics(values=[]){metricState=Object.fromEntries(values.map(x=>[x.id,x]));if(!topologyEditing)renderTopology();$('#metrics').innerHTML=(config.monitoring?.metrics||[]).map(m=>{const x=metricState[m.id]||{value:'--'},d=m.display||{},good=(d.goodValues||[]).includes(String(x.value));let bad=x.ok===false||(d.warnBelow!=null&&Number(x.value)<d.warnBelow);return `<article class="metric"><div class="metric-head"><span>${esc(m.name)}</span><span>${esc(m.group||'GLOBAL')}</span></div><div class="metric-value ${good?'good':bad?'bad':''}">${esc(x.value)} <small>${esc(d.unit||'')}</small></div><div class="metric-foot">${x.updatedAt?'更新于 '+new Date(x.updatedAt).toLocaleTimeString():'等待首次采集'}</div></article>`}).join('')||'<p>当前配置没有监控指标</p>'}
async function updateMetrics(){try{renderMetrics((await api('/api/metrics')).metrics)}catch(e){}}
function selectedTest(){return (config.tests||[]).find(t=>t.id===$('#testSelect').value)}
function updateScriptPreview(){const test=selectedTest();if(!test)return;const values=Object.fromEntries([...$('#testParams').querySelectorAll('input,select')].map(x=>[x.name,x.value]));$('#testScript').textContent=String(test.command||'').replace(/\{([A-Za-z_][A-Za-z0-9_]*)\}/g,(m,k)=>values[k]??m)}
function renderSelectedTest(){const test=selectedTest();if(!test)return;$('#testDescription').textContent=test.description||'无测试说明';$('#testParams').innerHTML=(test.params||[]).map(p=>{const control=p.choices?`<select name="${esc(p.name)}">${p.choices.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}</select>`:`<input name="${esc(p.name)}" type="${p.type==='number'?'number':'text'}" value="${esc(p.default??'')}">`;return `<label>${esc(p.label||p.name)}${control}</label>`}).join('')||'<span class="no-params">此测试无需参数</span>';$('#testParams').querySelectorAll('input,select').forEach(x=>x.oninput=updateScriptPreview);updateScriptPreview()}
function renderTests(){const tests=config.tests||[],select=$('#testSelect'),empty=$('#noTests');select.innerHTML=tests.map(t=>`<option value="${esc(t.id)}">${esc(t.name)} (${esc(t.id)})</option>`).join('');const has=tests.length>0;$('.test-select-row').classList.toggle('hidden',!has);$('#testDescription').classList.toggle('hidden',!has);$('#testParams').classList.toggle('hidden',!has);$('.script-title').classList.toggle('hidden',!has);$('#testScript').classList.toggle('hidden',!has);empty.classList.toggle('hidden',has);if(has)renderSelectedTest()}
async function runTest(){const test=selectedTest();if(!test)return;try{const params=Object.fromEntries([...$('#testParams').querySelectorAll('input,select')].map(x=>[x.name,x.value]));const job=await api('/api/tests',{method:'POST',body:JSON.stringify({testId:test.id,params})});testJob=job.id;$('#testRun').classList.remove('hidden');$('#testOutput').textContent='';$('#runTitle').textContent=job.name;watchJob(job.id,'#testOutput',()=>testJob=null)}catch(e){toast(e.message)}}
function appendOutput(selector,lines){const out=$(selector);for(const l of lines){const span=document.createElement('span');span.className=l.stream;span.textContent=l.text+'\n';out.append(span)}out.scrollTop=out.scrollHeight}
function watchJob(id,selector,onDone=()=>{}){let cursor=0;const timer=setInterval(async()=>{try{const job=await api(`/api/jobs/${id}?after=${cursor}`);appendOutput(selector,job.lines);cursor=job.cursor;if(job.status!=='running'&&job.status!=='stopping'){clearInterval(timer);appendOutput(selector,[{stream:job.exitCode===0?'stdout':'stderr',text:`[结束] exit=${job.exitCode} status=${job.status}`}]);onDone(job)}}catch(e){clearInterval(timer);onDone({status:'failed'})}},250)}
function terminalWrite(data,className=''){const out=$('#terminalOutput'),clean=String(data).replace(/\x1b\][^\x07]*(?:\x07|\x1b\\)/g,'').replace(/\x1b\[[0-?]*[ -\/]*[@-~]/g,'');for(let index=0;index<clean.length;index++){const char=clean[index];if(char==='\b')terminalBuffer=terminalBuffer.slice(0,-1);else if(char==='\r'){if(clean[index+1]!=='\n')continue}else terminalBuffer+=char}if(terminalBuffer.length>200000)terminalBuffer=terminalBuffer.slice(-150000);out.textContent=terminalBuffer;out.classList.toggle('has-error',className==='stderr');out.scrollTop=out.scrollHeight}
function terminalSize(){const out=$('#terminalOutput'),style=getComputedStyle(out),charWidth=parseFloat(style.fontSize)*.62,lineHeight=parseFloat(style.lineHeight)||21;return{type:'resize',columns:Math.max(20,Math.floor(out.clientWidth/charWidth)-2),rows:Math.max(5,Math.floor(out.clientHeight/lineHeight))}}
function connectTerminal(){if(terminalSocket&&(terminalSocket.readyState===WebSocket.OPEN||terminalSocket.readyState===WebSocket.CONNECTING))return;$('#terminalStatus').textContent='连接中';const protocol=location.protocol==='https:'?'wss':'ws';terminalSocket=new WebSocket(`${protocol}://${location.host}/ws/terminal`);terminalSocket.onopen=()=>terminalSocket.send(JSON.stringify(terminalSize()));terminalSocket.onmessage=e=>{const message=JSON.parse(e.data);if(message.type==='ready'){terminalConnected=true;$('#terminalStatus').textContent='已连接';$('#terminalStop').classList.remove('hidden');$('#terminalOutput').focus()}else if(message.type==='output')terminalWrite(message.data);else if(message.type==='error')terminalWrite(`\n[终端错误] ${message.message}\n`,'stderr');else if(message.type==='exit')terminalWrite(`\n[会话结束] exit=${message.code}\n`,'stderr')};terminalSocket.onclose=()=>{terminalConnected=false;$('#terminalStatus').textContent='已断开';$('#terminalStop').classList.add('hidden');terminalSocket=null};terminalSocket.onerror=()=>terminalWrite('\n[WebSocket 连接失败]\n','stderr')}
function terminalSend(data){if(!terminalConnected){connectTerminal();toast('终端正在连接');return false}terminalSocket.send(JSON.stringify({type:'input',data}));return true}
function resetTerminal(){if(terminalSocket)terminalSocket.close();terminalSocket=null;terminalConnected=false;$('#terminalStatus').textContent='已断开'}
const terminalKeys={Enter:'\r',Backspace:'\x7f',Tab:'\t',Escape:'\x1b',ArrowUp:'\x1b[A',ArrowDown:'\x1b[B',ArrowRight:'\x1b[C',ArrowLeft:'\x1b[D',Home:'\x1b[H',End:'\x1b[F',Delete:'\x1b[3~',Insert:'\x1b[2~',PageUp:'\x1b[5~',PageDown:'\x1b[6~'};
$('#terminalOutput').onkeydown=e=>{let data=terminalKeys[e.key];if(e.ctrlKey&&e.key.length===1){const code=e.key.toUpperCase().charCodeAt(0);if(code>=64&&code<=95)data=String.fromCharCode(code-64)}else if(!e.ctrlKey&&!e.metaKey&&e.key.length===1)data=(e.altKey?'\x1b':'')+e.key;if(data!==undefined){e.preventDefault();terminalSend(data)}};
$('#terminalOutput').onpaste=e=>{e.preventDefault();terminalSend(e.clipboardData.getData('text'))};
$('#terminalShell').onclick=e=>{if(!e.target.closest('button'))$('#terminalOutput').focus()};
window.addEventListener('resize',()=>{if(terminalConnected)terminalSocket.send(JSON.stringify(terminalSize()))});
window.addEventListener('beforeunload',()=>terminalSocket?.close());
$('#clearTerminal').onclick=()=>{terminalBuffer='';$('#terminalOutput').textContent=''};
$('#testSelect').onchange=renderSelectedTest;$('#runSelectedTest').onclick=runTest;
$('#editTopology').onclick=()=>{topologyEditing=true;$('#topology').classList.add('editing');$('#topologyEditor').classList.remove('hidden');$('#editTopology').classList.add('hidden');refreshTopologyEditor();renderTopology()};
$('#cancelTopology').onclick=async()=>{try{await api('/api/config/reload',{method:'POST',body:'{}'});topologyEditing=false;selectedTopologyNode=null;$('#topology').classList.remove('editing');$('#topologyEditor').classList.add('hidden');$('#editTopology').classList.remove('hidden');await load();toast('已放弃拓扑修改')}catch(e){toast(e.message)}};
$('#saveTopology').onclick=async()=>{try{await api('/api/config/save',{method:'POST',body:JSON.stringify({config})});topologyEditing=false;selectedTopologyNode=null;$('#topology').classList.remove('editing');$('#topologyEditor').classList.add('hidden');$('#editTopology').classList.remove('hidden');await load();toast('拓扑配置已保存')}catch(e){toast('保存失败：'+e.message)}};
$('#topologyNodeSelect').onchange=e=>{selectedTopologyNode=e.target.value;refreshTopologyEditor();renderTopology()};
for(const id of ['topologyNodeLabel','topologyNodeSubtitle','topologyNodeType','topologyNodeX','topologyNodeY'])$('#'+id).oninput=updateTopologyNode;
$('#addTopologyNode').onclick=()=>{const topology=config.topology||(config.topology={nodes:[],edges:[]});let index=1,id='node1';while(topology.nodes.some(n=>n.id===id))id='node'+(++index);topology.nodes.push({id,type:'device',label:'New Node',x:50,y:50});selectedTopologyNode=id;refreshTopologyEditor();renderTopology()};
$('#deleteTopologyNode').onclick=()=>{const topology=config.topology,node=topologyNode();if(!topology||!node)return;topology.nodes=topology.nodes.filter(n=>n.id!==node.id);topology.edges=(topology.edges||[]).filter(e=>e.from!==node.id&&e.to!==node.id);selectedTopologyNode=topology.nodes[0]?.id||null;refreshTopologyEditor();renderTopology()};
$('#addTopologyEdge').onclick=()=>{const topology=config.topology||(config.topology={nodes:[],edges:[]}),from=$('#edgeFrom').value,to=$('#edgeTo').value;if(!from||!to||from===to){toast('请选择两个不同节点');return}if(topology.edges.some(e=>e.from===from&&e.to===to)){toast('这条连接已经存在');return}const edge={from,to},link=$('#edgeLinkMetric').value,video=$('#edgeVideoMetric').value;if(link)edge.linkMetric=link;if(video)edge.videoMetric=video;topology.edges.push(edge);refreshTopologyEditor();renderTopology()};
$('#terminalStop').onclick=()=>{if(terminalSend('\x03'))toast('已发送 Ctrl+C')};
$('#stopJob').onclick=async()=>{if(testJob)await api(`/api/jobs/${testJob}/stop`,{method:'POST',body:'{}'})};
$('#reloadConfig').onclick=async()=>{try{await api('/api/config/reload',{method:'POST',body:'{}'});await load();toast('配置已重新加载')}catch(e){toast(e.message)}};
$('#formatConfig').onclick=()=>{try{$('#configPreview').value=JSON.stringify(JSON.parse($('#configPreview').value),null,2)}catch(e){toast('JSON 格式错误：'+e.message)}};
$('#saveConfig').onclick=async()=>{try{const edited=JSON.parse($('#configPreview').value);await api('/api/config/save',{method:'POST',body:JSON.stringify({config:edited})});await load();toast('平台配置已保存并生效')}catch(e){toast('保存失败：'+e.message)}};
$('#switchProfile').onclick=async()=>{try{const file=$('#profileSelect').value;if(!file)return;await api('/api/config/switch',{method:'POST',body:JSON.stringify({file})});resetTerminal();await load();toast('已切换平台配置')}catch(e){toast(e.message)}};
async function saveTarget(){const form=$('#sshForm'),data=Object.fromEntries(new FormData(form));await api('/api/config/target',{method:'POST',body:JSON.stringify(data)});resetTerminal();await load();return data}
$('#sshForm').onsubmit=async e=>{e.preventDefault();try{await saveTarget();toast(config.target.transport==='ssh'?'SSH 配置已保存，终端已切换到远程':'已切换为本机模式')}catch(err){toast(err.message)}};
$('#testConnection').onclick=async()=>{const result=$('#connectionResult');result.className='';result.textContent='正在保存配置…';try{const selected=$('#sshForm').elements.transport.value;if(selected!=='ssh'){result.className='bad';result.textContent='当前是 Local 本机模式';toast('请选择 SSH（远程开发板）');return}await saveTarget();result.textContent='正在连接远程开发板…';const job=await api('/api/connection/test',{method:'POST',body:'{}'});let cursor=0;const timer=setInterval(async()=>{try{const state=await api(`/api/jobs/${job.id}?after=${cursor}`);cursor=state.cursor;if(state.status!=='running'){clearInterval(timer);const ok=state.status==='success';result.className=ok?'good':'bad';result.textContent=ok?`✓ SSH 已连接，终端目标：${config.target.user||''}@${config.target.host}`:'✕ SSH 连接失败';if(!ok)toast(state.lines.map(x=>x.text).join(' ')||'SSH 连接失败')}}catch(e){clearInterval(timer);result.className='bad';result.textContent='✕ '+e.message}},250)}catch(e){result.className='bad';result.textContent='✕ '+e.message}};
async function load(){config=await api('/api/config');$('#targetName').textContent=config.project?.name||'未命名项目';$('#targetHost').textContent=config.target?.transport==='local'?'Local':`${config.target?.user||''}@${config.target?.host||'未配置'}`;$('#terminalTarget').textContent=$('#targetHost').textContent;const form=$('#sshForm'),target=config.target||{};for(const name of ['transport','host','port','user','password','identityFile','connectTimeout'])if(form.elements[name])form.elements[name].value=target[name]??(name==='port'?22:name==='connectTimeout'?8:'');$('#configInfo').innerHTML=`<dt>配置文件</dt><dd>${esc(config.configPath)}</dd><dt>平台</dt><dd>${esc(config.project?.platform||'通用')}</dd><dt>传输层</dt><dd>${esc(config.target?.transport||'ssh')}</dd><dt>监控指标</dt><dd>${config.monitoring?.metrics?.length||0} 项</dd><dt>测试任务</dt><dd>${config.tests?.length||0} 项</dd>`;const preview={...config};delete preview.configPath;$('#configPreview').value=JSON.stringify(preview,null,2);const profileData=await api('/api/config/profiles');$('#profileSelect').innerHTML=profileData.profiles.map(p=>`<option value="${esc(p.file)}" ${p.active?'selected':''}>${esc(p.name)} · ${esc(p.platform)}</option>`).join('');renderMetrics();renderTests()}
setInterval(updateMetrics,1000);setInterval(()=>$('#clock').textContent=new Date().toLocaleString(),1000);load().catch(e=>toast(e.message));
