const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
if(location.protocol==='file:') $('#fileWarning').classList.remove('hidden');
let config={}, activeJob=null, jobCursor=0, jobTimer=null;
const titles={dashboard:['监控看板','实时掌握相机链路运行状态'],terminal:['命令终端','通过 SSH 执行远端指令并查看实时输出'],tests:['测试中心','配置化运行、观察和停止测试脚本'],settings:['平台配置','一个内核，适配不同芯片与项目']};
async function api(path,options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const d=await r.json();if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}
function toast(s){const e=$('#toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showPage(id){$$('.page,nav button').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$(`nav button[data-page="${id}"]`).classList.add('active');$('#pageTitle').textContent=titles[id][0];$('#subtitle').textContent=titles[id][1]}
$$('nav button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
function renderMetrics(values=[]){const map=Object.fromEntries(values.map(x=>[x.id,x]));$('#metrics').innerHTML=(config.monitoring?.metrics||[]).map(m=>{const x=map[m.id]||{value:'--'},d=m.display||{},good=(d.goodValues||[]).includes(String(x.value));let bad=x.ok===false||(d.warnBelow!=null&&Number(x.value)<d.warnBelow);return `<article class="metric"><div class="metric-head"><span>${esc(m.name)}</span><span>${esc(m.group||'GLOBAL')}</span></div><div class="metric-value ${good?'good':bad?'bad':''}">${esc(x.value)} <small>${esc(d.unit||'')}</small></div><div class="metric-foot">${x.updatedAt?'更新于 '+new Date(x.updatedAt).toLocaleTimeString():'等待首次采集'}</div></article>`}).join('')||'<p>当前配置没有监控指标</p>'}
async function updateMetrics(){try{renderMetrics((await api('/api/metrics')).metrics)}catch(e){}}
function renderTests(){const root=$('#testList');root.innerHTML=(config.tests||[]).map(t=>`<article class="test panel" data-id="${esc(t.id)}"><h3>${esc(t.name)}</h3><p>${esc(t.description||'')}</p>${(t.params||[]).map(p=>`<label>${esc(p.label||p.name)}<input name="${esc(p.name)}" type="${p.type==='number'?'number':'text'}" value="${esc(p.default??'')}"></label>`).join('')}<button>运行测试</button></article>`).join('')||'<p>当前配置没有测试任务。</p>';root.querySelectorAll('button').forEach(b=>b.onclick=()=>runTest(b.closest('.test')))}
async function runTest(card){try{const params=Object.fromEntries([...card.querySelectorAll('input')].map(x=>[x.name,x.value]));const job=await api('/api/tests',{method:'POST',body:JSON.stringify({testId:card.dataset.id,params})});$('#testRun').classList.remove('hidden');$('#testOutput').textContent='';$('#runTitle').textContent=job.name;watchJob(job.id,'#testOutput')}catch(e){toast(e.message)}}
function appendOutput(selector,lines){const out=$(selector);for(const l of lines){const span=document.createElement('span');span.className=l.stream;span.textContent=l.text+'\n';out.append(span)}out.scrollTop=out.scrollHeight}
function watchJob(id,selector){activeJob=id;jobCursor=0;clearInterval(jobTimer);jobTimer=setInterval(async()=>{try{const job=await api(`/api/jobs/${id}?after=${jobCursor}`);appendOutput(selector,job.lines);jobCursor=job.cursor;if(job.status!=='running'&&job.status!=='stopping'){clearInterval(jobTimer);appendOutput(selector,[{stream:job.exitCode===0?'stdout':'stderr',text:`[结束] exit=${job.exitCode} status=${job.status}`}]);activeJob=null}}catch(e){clearInterval(jobTimer)}},250)}
$('#commandForm').onsubmit=async e=>{e.preventDefault();const input=$('#commandInput'),cmd=input.value.trim();if(!cmd)return;appendOutput('#terminalOutput',[{stream:'cmd',text:`$ ${cmd}`}]);input.value='';try{const job=await api('/api/commands',{method:'POST',body:JSON.stringify({command:cmd})});watchJob(job.id,'#terminalOutput')}catch(e){appendOutput('#terminalOutput',[{stream:'stderr',text:e.message}])}};
$('#clearTerminal').onclick=()=>$('#terminalOutput').innerHTML='';$('#stopJob').onclick=async()=>{if(activeJob)await api(`/api/jobs/${activeJob}/stop`,{method:'POST',body:'{}'})};
$('#reloadConfig').onclick=async()=>{try{await api('/api/config/reload',{method:'POST',body:'{}'});await load();toast('配置已重新加载')}catch(e){toast(e.message)}};
async function load(){config=await api('/api/config');$('#targetName').textContent=config.project?.name||'未命名项目';$('#targetHost').textContent=config.target?.transport==='local'?'Local':`${config.target?.user||''}@${config.target?.host||'未配置'}`;$('#terminalTarget').textContent=$('#targetHost').textContent;$('#configInfo').innerHTML=`<dt>配置文件</dt><dd>${esc(config.configPath)}</dd><dt>平台</dt><dd>${esc(config.project?.platform||'通用')}</dd><dt>传输层</dt><dd>${esc(config.target?.transport||'ssh')}</dd><dt>监控指标</dt><dd>${config.monitoring?.metrics?.length||0} 项</dd><dt>测试任务</dt><dd>${config.tests?.length||0} 项</dd>`;const preview={...config};delete preview.configPath;$('#configPreview').textContent=JSON.stringify(preview,null,2);renderMetrics();renderTests()}
setInterval(updateMetrics,1000);setInterval(()=>$('#clock').textContent=new Date().toLocaleString(),1000);load().catch(e=>toast(e.message));
