import {api, getAccessToken, hideAccessToken, initAuth} from './api.js';
import {createDiagnostics} from './diagnostics.js';
import {createConfigEditor} from './config-editor.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
document.body.dataset.page='dashboard';
if(location.protocol==='file:') $('#fileWarning').classList.remove('hidden');
let config={}, terminalSocket=null, terminalConnected=false, testJob=null, pytestLoaded=false, platformScriptsLoaded=false, manualLoaded=false, metricState={}, topologyEditing=false, metricEditing=false, selectedTopologyNode=null, topologyZoom=1;
const xterm=new window.Terminal({cursorBlink:true,cursorStyle:'bar',fontFamily:'"Cascadia Mono","Microsoft YaHei UI",Consolas,monospace',fontSize:14,lineHeight:1.2,scrollback:10000,convertEol:false,allowTransparency:true,theme:{background:'#080d13',foreground:'#dce7f2',cursor:'#4de1d1',cursorAccent:'#080d13',selectionBackground:'#2f5f8877',black:'#10151c',red:'#ff6b78',green:'#58d68d',yellow:'#ffbd5a',blue:'#55a7ff',magenta:'#c792ea',cyan:'#4de1d1',white:'#eaf1f8',brightBlack:'#607086'}});
const terminalFitAddon=new window.FitAddon.FitAddon();
const terminalSearchAddon=new window.SearchAddon.SearchAddon();
xterm.loadAddon(terminalFitAddon);
xterm.loadAddon(terminalSearchAddon);
xterm.open($('#terminalOutput'));
let terminalLineBuffer='',sftpPath='/',sftpLoaded=false;
let terminalHistory=JSON.parse(localStorage.getItem('cameraDebugTerminalHistory')||'[]');
let quickCommands=JSON.parse(localStorage.getItem('cameraDebugQuickCommands')||'[{"name":"进程","command":"ps aux"},{"name":"磁盘","command":"df -h"},{"name":"日志","command":"dmesg | tail -n 50"}]');
let selectedMetricIndex=0;
const titles={dashboard:['监控看板','实时掌握相机链路运行状态'],terminal:['命令终端','通过 SSH 执行远端指令并查看实时输出'],tests:['测试中心','配置化运行、观察和停止测试脚本'],settings:['平台配置','一个内核，适配不同芯片与项目'],diagnostics:['诊断信息','运行状态、错误与任务历史'],manual:['用户手册','工具介绍、操作方法与平台配置参考']};
function toast(s){const e=$('#toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const configEditor=createConfigEditor({api,toast,escapeHtml:esc});
function showPage(id){const current=$('.page.active')?.id;if(current==='settings'&&id!=='settings'&&!configEditor.confirmDiscard('离开平台配置页面'))return;document.body.dataset.page=id;$$('.page,nav button').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$(`nav button[data-page="${id}"]`).classList.add('active');$('#pageTitle').textContent=titles[id][0];$('#subtitle').textContent=titles[id][1];if(id==='manual'&&!manualLoaded)loadManual();if(id==='tests'){if(!platformScriptsLoaded)loadPlatformScripts();if(!pytestLoaded)loadPytests();}if(id==='diagnostics')loadDiagnostics();if(id==='terminal'){fitTerminal();connectTerminal();if(!sftpLoaded)loadSftp(sftpPath);setTimeout(()=>xterm.focus())}}
$$('nav button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
$('.connection-panel>p').textContent='支持私钥或密码认证。配置接口不会返回已保存的密码。';
$('#sshForm [name="password"]').placeholder='留空则保留已有密码或使用私钥';
$('#sshForm [name="password"]+small').textContent='留空保存会保留已有密码；页面仅显示是否已配置';
$('#dashboard').insertAdjacentHTML('beforeend',`<div id="metricEditor" class="panel metric-config-panel hidden"><div class="metric-editor-head"><div><h2>监控指标编辑模式</h2><p>配置“详细指标”的采集命令、解析规则和展示条件。</p></div><div><button id="newMetric" class="secondary">＋ 新增指标</button><button id="cancelMetric" class="secondary">取消</button><button id="saveMetric">保存指标</button></div></div><div class="metric-editor-body"><aside class="metric-config-list"><div id="metricConfigList"></div></aside><form id="metricForm"><div class="form-row metric-basic"><label>指标 ID<input name="id" required placeholder="camera_link_0"></label><label>显示名称<input name="name" required placeholder="Camera 0 Link"></label></div><div class="form-row metric-basic"><label>分组<input name="group" placeholder="CAMERA 0"></label><label class="check-label"><input name="enabled" type="checkbox" checked>启用定时采集</label></div><label>采集命令<textarea name="command" required placeholder="i2cdbgr r {bus} {device} {register}"></textarea><small>支持使用 variables.json 中的 <code>{变量名}</code></small></label><div class="form-row metric-timing"><label>采集周期（秒）<input name="interval" type="number" min="0.1" step="0.1" value="2"></label><label>超时（秒）<input name="timeout" type="number" min="0.1" step="0.1" value="5"></label><label>解析类型<select name="parserType"><option value="text">原始文本</option><option value="regex">正则表达式</option><option value="number">数值</option></select></label></div><div class="parser-fields"><label>匹配表达式<input name="pattern" placeholder="例如：0x([0-9A-Fa-f]+)"></label><label>捕获组<input name="groupIndex" type="number" min="0" value="1"></label></div><label>结果映射<textarea name="mapping" placeholder="1=LOCKED&#10;0=UNLOCKED"></textarea><small>每行填写“原始值=显示值”</small></label><div class="form-row metric-display"><label>展示类型<select name="displayKind"><option value="status">状态</option><option value="value">数值</option></select></label><label>单位<input name="unit" placeholder="fps / ℃"></label><label>数值告警下限<input name="warnBelow" type="number" step="any" placeholder="可选"></label></div><label>正常值<textarea name="goodValues" placeholder="LOCKED&#10;ONLINE"></textarea><small>每行一个正常值，也可使用逗号分隔</small></label><div class="metric-form-actions"><button type="button" id="deleteMetric" class="danger">删除指标</button><button type="button" id="reloadMetric" class="secondary">恢复当前指标</button></div></form></div></div>`);
$('#topologyEditor .editor-head').insertAdjacentHTML('afterend',`<div class="canvas-settings"><label>画布高度（px）<input id="topologyHeight" type="number" min="400" max="1600" step="20"></label><button id="autoTopologyHeight" class="secondary">根据节点数自动调整</button><small>宽度随窗口自动适应；增加高度可容纳更多 Camera。</small></div>`);
$('#topologyEditor .node-position').insertAdjacentHTML('beforeend',`<label>宽度（px）<input id="topologyNodeWidth" type="number" min="56" max="320" step="2"></label><label>高度（px）<input id="topologyNodeHeight" type="number" min="48" max="260" step="2"></label>`);
function topologyHeight(){return Math.max(400,Math.min(1600,Number(config.topology?.height)||520))}
function applyTopologyHeight(){const height=topologyHeight();$('#topology').style.height=height+'px';if($('#topologyHeight'))$('#topologyHeight').value=height}
function applyTopologyZoom(){const viewport=$('#topologyViewport'),stage=$('#topologyStage');if(viewport&&stage){stage.style.height=(topologyHeight()*topologyZoom)+'px';viewport.style.width=(100/topologyZoom)+'%';viewport.style.height=topologyHeight()+'px';viewport.style.transform=`scale(${topologyZoom})`}$('#topologyZoomValue').textContent=Math.round(topologyZoom*100)+'%';$('#topologyZoomOut').disabled=topologyZoom<=.2;$('#topologyZoomIn').disabled=topologyZoom>=2}
function setTopologyZoom(value){topologyZoom=Math.max(.2,Math.min(2,Math.round(value*20)/20));applyTopologyZoom()}
function fitTopology(){const panel=$('#topology');setTopologyZoom(panel.clientHeight/topologyHeight());panel.scrollTop=0;panel.scrollLeft=0}
function manualInline(text){return esc(text).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>')}
function renderManual(markdown){const lines=markdown.split(/\r?\n/),html=[];let code=[],inCode=false,list=null,headingIndex=0;const closeList=()=>{if(list){html.push(`</${list}>`);list=null}};for(const line of lines){if(line.startsWith('```')){if(inCode){html.push(`<pre><code>${esc(code.join('\n'))}</code></pre>`);code=[];inCode=false}else{closeList();inCode=true}continue}if(inCode){code.push(line);continue}const heading=line.match(/^(#{1,3})\s+(.+)$/);if(heading){closeList();const level=heading[1].length,id=`manual-heading-${headingIndex++}`;html.push(`<h${level} id="${id}">${manualInline(heading[2])}</h${level}>`);continue}const bullet=line.match(/^[-*]\s+(.+)$/),ordered=line.match(/^\d+\.\s+(.+)$/);if(bullet||ordered){const wanted=bullet?'ul':'ol';if(list!==wanted){closeList();list=wanted;html.push(`<${list}>`)}html.push(`<li>${manualInline((bullet||ordered)[1])}</li>`);continue}closeList();if(/^\|.*\|$/.test(line)&&!/^\|[-: |]+\|$/.test(line)){const cells=line.slice(1,-1).split('|').map(x=>`<span>${manualInline(x.trim())}</span>`).join('');html.push(`<div class="manual-table-row">${cells}</div>`)}else if(line.trim()){html.push(`<p>${manualInline(line)}</p>`)}}closeList();$('#manualContent').innerHTML=html.join('');const headings=[...$('#manualContent').querySelectorAll('h2')];$('#manualToc').innerHTML=headings.map(h=>`<a href="#${h.id}">${h.textContent}</a>`).join('')}
async function loadManual(){try{const data=await api('/api/manual');renderManual(data.content);manualLoaded=true}catch(e){$('#manualContent').innerHTML=`<p class="stderr">${esc(e.message)}</p>`}}
function topologyMetric(id){return id?metricState[id]:null}
function positiveState(metric,kind){if(!metric||metric.ok===false)return false;const value=String(metric.value).toUpperCase();const accepted=kind==='video'?['VIDEO LOCK','VIDEO_LOCK','STREAMING','LOCKED','ONLINE','1','0X1']:['LINK LOCK','LINK_LOCK','LOCKED','ONLINE','1','0X1'];return accepted.includes(value)}
function edgeState(edge){const link=topologyMetric(edge.linkMetric),video=topologyMetric(edge.videoMetric);if(!link)return'unknown';if(!positiveState(link,'link'))return'lost';return positiveState(video,'video')?'video':'linked'}
function renderTopology(){const topology=config.topology;if(!topology||!Array.isArray(topology.nodes)||!topology.nodes.length){$('#topology').innerHTML='<div class="topology-empty">当前平台未配置拓扑图</div>';return}const nodes=Object.fromEntries(topology.nodes.map(n=>[n.id,n])),edges=topology.edges||[],nodeStates={};const edgeMarkup=edges.map(edge=>{const a=nodes[edge.from],b=nodes[edge.to];if(!a||!b)return'';const state=edgeState(edge);(nodeStates[a.id]??=[]).push(state);(nodeStates[b.id]??=[]).push(state);const x1=Number(a.x),y1=Number(a.y),x2=Number(b.x),y2=Number(b.y),mx=(x1+x2)/2,my=(y1+y2)/2,label=state==='video'?'VIDEO LOCK':state==='linked'?'LINK LOCK':state==='lost'?'LINK LOST':'WAITING';return `<g class="topology-edge ${state}"><path d="M ${x1} ${y1} L ${x2} ${y2}"/>${state==='video'?`<path class="data-flow" d="M ${x1} ${y1} L ${x2} ${y2}"/>`:''}</g>`}).join('');const nodeMarkup=topology.nodes.map(node=>{const x=Math.max(0,Math.min(100,Number(node.x))),y=Math.max(0,Math.min(100,Number(node.y))),states=nodeStates[node.id]||[],hasGood=states.includes('video')||states.includes('linked');const state=states.includes('lost')&&hasGood?'degraded':states.includes('video')?'video':states.includes('linked')?'linked':states.includes('lost')?'lost':'unknown';const status={video:'STREAMING',linked:'LINKED',lost:'LOST',degraded:'DEGRADED',unknown:'UNKNOWN'}[state];return `<div data-node-id="${esc(node.id)}" class="topology-node ${esc(node.type||'device')} ${state} ${topologyEditing&&selectedTopologyNode===node.id?'selected':''}" style="left:${x}%;top:${y}%"><span>${esc(node.label||node.id)}</span>${node.subtitle?`<small>${esc(node.subtitle)}</small>`:''}<b>${status}</b></div>`}).join('');$('#topology').innerHTML=`<svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Camera connection topology">${edgeMarkup}</svg>${nodeMarkup}`;if(topologyEditing)bindTopologyDrag()}
function topologyNodeDimensions(node){const defaults=node?.type==='camera'?[88,88]:node?.type==='soc'?[150,170]:[132,78];return{width:Math.max(56,Math.min(320,Number(node?.width)||defaults[0])),height:Math.max(48,Math.min(260,Number(node?.height)||defaults[1]))}}
function bindTopologyResize(element,node){const handle=element.querySelector('.node-resize-handle');if(!handle)return;handle.onpointerdown=event=>{event.preventDefault();event.stopPropagation();selectedTopologyNode=node.id;$$('#topology .topology-node').forEach(item=>item.classList.toggle('selected',item===element));refreshTopologyEditor();const startX=event.clientX,startY=event.clientY,start=topologyNodeDimensions(node);const move=e=>{node.width=Math.max(56,Math.min(320,Math.round(start.width+e.clientX-startX)));node.height=Math.max(48,Math.min(260,Math.round(start.height+e.clientY-startY)));element.style.width=node.width+'px';element.style.height=node.height+'px';element.style.minHeight=node.height+'px';$('#topologyNodeWidth').value=node.width;$('#topologyNodeHeight').value=node.height};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);renderTopology()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}}
const renderTopologyWithoutSizing=renderTopology;renderTopology=()=>{applyTopologyHeight();renderTopologyWithoutSizing();for(const element of $$('#topology .topology-node')){const node=config.topology?.nodes?.find(item=>item.id===element.dataset.nodeId),dimensions=topologyNodeDimensions(node);element.style.width=dimensions.width+'px';element.style.height=dimensions.height+'px';element.style.minHeight=dimensions.height+'px';if(topologyEditing){element.insertAdjacentHTML('beforeend','<i class="node-resize-handle" title="拖动调整节点宽度和高度"></i>');bindTopologyResize(element,node)}}};
const refreshTopologyEditorWithoutSize=refreshTopologyEditor;refreshTopologyEditor=()=>{refreshTopologyEditorWithoutSize();const dimensions=topologyNodeDimensions(topologyNode());$('#topologyNodeWidth').value=dimensions.width;$('#topologyNodeHeight').value=dimensions.height};
const renderTopologyWithoutZoom=renderTopology;renderTopology=()=>{renderTopologyWithoutZoom();const topology=$('#topology');if(!$('#topologyViewport')&&topology.querySelector('svg,.topology-node')){const stage=document.createElement('div'),viewport=document.createElement('div');stage.id='topologyStage';stage.className='topology-stage';viewport.id='topologyViewport';viewport.className='topology-viewport';while(topology.firstChild)viewport.append(topology.firstChild);stage.append(viewport);topology.append(stage)}applyTopologyZoom()};
function topologyNode(id=selectedTopologyNode){return config.topology?.nodes?.find(n=>n.id===id)}
function bindTopologyDrag(){$$('#topology .topology-node').forEach(element=>{element.onpointerdown=event=>{event.preventDefault();selectedTopologyNode=element.dataset.nodeId;refreshTopologyEditor();renderTopology();const active=$$('#topology .topology-node').find(n=>n.dataset.nodeId===selectedTopologyNode),node=topologyNode(),box=($('#topologyViewport')||$('#topology')).getBoundingClientRect();const move=e=>{node.x=Math.max(3,Math.min(97,Math.round((e.clientX-box.left)/box.width*100)));node.y=Math.max(4,Math.min(96,Math.round((e.clientY-box.top)/box.height*100)));active.style.left=node.x+'%';active.style.top=node.y+'%';$('#topologyNodeX').value=node.x;$('#topologyNodeY').value=node.y};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);renderTopology()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}})}
function topologyOptions(items,selected='',empty=''){return `${empty?`<option value="">${esc(empty)}</option>`:''}${items.map(item=>`<option value="${esc(item.id)}" ${item.id===selected?'selected':''}>${esc(item.label||item.name||item.id)}</option>`).join('')}`}
function refreshTopologyEditor(){const topology=config.topology||(config.topology={nodes:[],edges:[]}),nodes=topology.nodes,metrics=config.monitoring?.metrics||[],previousFrom=$('#edgeFrom').value,previousTo=$('#edgeTo').value;if(selectedTopologyNode&&!topologyNode())selectedTopologyNode=null;if(!selectedTopologyNode&&nodes.length)selectedTopologyNode=nodes[0].id;$('#topologyNodeSelect').innerHTML=topologyOptions(nodes,selectedTopologyNode);const node=topologyNode();for(const [id,value] of [['topologyNodeLabel',node?.label||''],['topologyNodeSubtitle',node?.subtitle||''],['topologyNodeX',node?.x??''],['topologyNodeY',node?.y??'']])$('#'+id).value=value;$('#topologyNodeType').value=node?.type||'device';const nodeOpts=topologyOptions(nodes),validIds=new Set(nodes.map(item=>item.id)),nodeNames=Object.fromEntries(nodes.map(item=>[item.id,item.label||item.id])),from=validIds.has(previousFrom)?previousFrom:(selectedTopologyNode||nodes[0]?.id||''),to=validIds.has(previousTo)&&previousTo!==from?previousTo:(nodes.find(item=>item.id!==from)?.id||'');$('#edgeFrom').innerHTML=nodeOpts;$('#edgeTo').innerHTML=nodeOpts;$('#edgeFrom').value=from;$('#edgeTo').value=to;$('#addTopologyEdge').disabled=nodes.length<2;const metricOpts=topologyOptions(metrics,'','不绑定');$('#edgeLinkMetric').innerHTML=metricOpts;$('#edgeVideoMetric').innerHTML=metricOpts;$('#topologyEdgeList').innerHTML=(topology.edges||[]).map((edge,index)=>`<div class="edge-item"><span>${esc(nodeNames[edge.from]||edge.from)} → ${esc(nodeNames[edge.to]||edge.to)}<small>Link: ${esc(edge.linkMetric||'--')} · Video: ${esc(edge.videoMetric||'--')}</small></span><button data-edge-index="${index}">删除</button></div>`).join('')||'<span class="no-params">暂无连接</span>';$$('#topologyEdgeList button').forEach(button=>button.onclick=()=>{topology.edges.splice(Number(button.dataset.edgeIndex),1);refreshTopologyEditor();renderTopology()})}
function updateTopologyNode(){const node=topologyNode();if(!node)return;node.label=$('#topologyNodeLabel').value.trim()||node.id;node.subtitle=$('#topologyNodeSubtitle').value.trim();node.type=$('#topologyNodeType').value;node.x=Math.max(0,Math.min(100,Number($('#topologyNodeX').value)||0));node.y=Math.max(0,Math.min(100,Number($('#topologyNodeY').value)||0));node.width=Math.max(56,Math.min(320,Number($('#topologyNodeWidth').value)||topologyNodeDimensions(node).width));node.height=Math.max(48,Math.min(260,Number($('#topologyNodeHeight').value)||topologyNodeDimensions(node).height));delete node.size;renderTopology();refreshTopologyEditor()}
function refreshMetricGroups(){const select=$('#metricGroup'),selected=select.value,groups=[...new Set((config.monitoring?.metrics||[]).map(item=>item.group||'GLOBAL'))].sort(),signature=groups.join('\u0000');if(select.dataset.groups===signature)return;select.dataset.groups=signature;select.innerHTML='<option value="">全部</option>'+groups.map(group=>`<option value="${esc(group)}">${esc(group)}</option>`).join('');if(groups.includes(selected))select.value=selected}
function renderMetrics(values=[]){refreshMetricGroups();metricState=Object.fromEntries(values.map(x=>[x.id,x]));if(!topologyEditing)renderTopology();const selectedGroup=$('#metricGroup').value,visibleMetrics=(config.monitoring?.metrics||[]).filter(m=>!selectedGroup||(m.group||'GLOBAL')===selectedGroup);$('#metrics').innerHTML=visibleMetrics.map(m=>{const x=metricState[m.id]||{value:'--'},d=m.display||{},good=(d.goodValues||[]).includes(String(x.value));let bad=x.ok===false||(d.warnBelow!=null&&Number(x.value)<d.warnBelow),state=x.stale?'数据过期':x.ok===false?`${x.errorCode||'采集失败'} · 连续 ${x.failureCount||1} 次`:x.updatedAt?`${x.durationMs||0} ms`:'等待采集';return `<article class="metric ${x.stale?'stale':''}"><div class="metric-head"><span>${esc(m.name)}</span><span>${esc(m.group||'GLOBAL')}</span></div><div class="metric-value ${good?'good':bad?'bad':''}">${esc(x.value)} <small>${esc(d.unit||'')}</small></div><div class="metric-foot">${esc(state)}</div></article>`}).join('')||'<p>当前配置没有监控指标</p>'}
function metricList(){return config.monitoring?.metrics||(config.monitoring={metrics:[]}).metrics}
function setMetricEditing(enabled){metricEditing=enabled;$('#metricEditor').classList.toggle('hidden',!enabled);$('#editMetrics').classList.toggle('hidden',enabled);if(enabled){selectedMetricIndex=Math.max(0,Math.min(selectedMetricIndex,metricList().length-1));fillMetricForm();$('#metricEditor').scrollIntoView({behavior:'smooth',block:'start'})}}
function mappingText(map={}){return Object.entries(map).map(([key,value])=>`${key}=${value}`).join('\n')}
function fillMetricForm(){const metrics=metricList(),metric=metrics[selectedMetricIndex],form=$('#metricForm');$('#metricConfigList').innerHTML=metrics.map((item,index)=>`<button type="button" data-metric-index="${index}" class="${index===selectedMetricIndex?'active':''}"><span>${esc(item.name||item.id)}</span><small>${esc(item.id)}</small></button>`).join('')||'<div class="empty-state">暂无指标，点击“新增指标”开始配置</div>';$$('#metricConfigList button').forEach(button=>button.onclick=()=>{selectedMetricIndex=Number(button.dataset.metricIndex);fillMetricForm()});form.classList.toggle('disabled',!metric);for(const control of form.elements)control.disabled=!metric;if(!metric)return;const parser=metric.parser||{type:'text'},display=metric.display||{};const values={id:metric.id||'',name:metric.name||'',group:metric.group||'',command:metric.command||'',interval:metric.interval??2,timeout:metric.timeout??5,parserType:parser.type||'text',pattern:parser.pattern||'',groupIndex:parser.group??1,mapping:mappingText(parser.map),displayKind:display.kind||'status',unit:display.unit||'',warnBelow:display.warnBelow??'',goodValues:(display.goodValues||[]).join('\n')};for(const [name,value] of Object.entries(values))form.elements[name].value=value;form.elements.enabled.checked=metric.enabled!==false;toggleParserFields()}
function toggleParserFields(){const type=$('#metricForm').elements.parserType.value;$('.parser-fields').classList.toggle('hidden',type==='text');$('#metricForm').elements.groupIndex.closest('label').classList.toggle('hidden',type!=='regex')}
function parseMapping(text){const result={};for(const raw of text.split(/\r?\n/)){const line=raw.trim();if(!line)continue;const index=line.indexOf('=');if(index<1)throw Error(`映射格式错误：${line}`);result[line.slice(0,index).trim()]=line.slice(index+1).trim()}return result}
async function saveMetric(){const metrics=metricList(),old=metrics[selectedMetricIndex];if(!old){toast('请先新增一个指标');return}const form=$('#metricForm'),id=form.elements.id.value.trim(),name=form.elements.name.value.trim(),command=form.elements.command.value.trim();if(!/^[A-Za-z0-9_-]+$/.test(id)){toast('指标 ID 只能包含字母、数字、下划线和连字符');return}if(metrics.some((item,index)=>index!==selectedMetricIndex&&item.id===id)){toast('指标 ID 已存在');return}if(!name||!command){toast('显示名称和采集命令不能为空');return}try{const parserType=form.elements.parserType.value,parser={...old.parser,type:parserType},map=parseMapping(form.elements.mapping.value);if(parserType!=='text'){const pattern=form.elements.pattern.value.trim();if(!pattern)throw Error('当前解析类型需要填写匹配表达式');parser.pattern=pattern}else delete parser.pattern;if(parserType==='regex')parser.group=Number(form.elements.groupIndex.value)||0;else delete parser.group;if(Object.keys(map).length)parser.map=map;else delete parser.map;const display={...old.display,kind:form.elements.displayKind.value},unit=form.elements.unit.value.trim(),warn=form.elements.warnBelow.value,goodValues=form.elements.goodValues.value.split(/[\n,]/).map(x=>x.trim()).filter(Boolean);if(unit)display.unit=unit;else delete display.unit;if(warn!=='')display.warnBelow=Number(warn);else delete display.warnBelow;if(goodValues.length)display.goodValues=goodValues;else delete display.goodValues;metrics[selectedMetricIndex]={...old,id,name,group:form.elements.group.value.trim(),command,enabled:form.elements.enabled.checked,interval:Number(form.elements.interval.value)||2,timeout:Number(form.elements.timeout.value)||5,parser,display};if(old.id!==id)for(const edge of config.topology?.edges||[]){if(edge.linkMetric===old.id)edge.linkMetric=id;if(edge.videoMetric===old.id)edge.videoMetric=id}await api('/api/config/save',{method:'POST',body:JSON.stringify({config})});await load();selectedMetricIndex=Math.max(0,metricList().findIndex(item=>item.id===id));setMetricEditing(false);toast('监控指标已保存并生效')}catch(e){toast('保存失败：'+e.message)}}
async function updateMetrics(){try{const data=await api('/api/metrics');renderMetrics(data.metrics);$('#toggleMonitoring').textContent=data.paused?'恢复监控':'暂停监控'}catch(e){}}
async function saveEmptyMetricList(){try{await api('/api/config/save',{method:'POST',body:JSON.stringify({config})});await load();setMetricEditing(false);toast('监控指标已保存并生效')}catch(e){toast('保存失败：'+e.message)}}
function selectedTest(){return (config.tests||[]).find(t=>t.id===$('#testSelect').value)}
function updateScriptPreview(){const test=selectedTest();if(!test)return;const values=Object.fromEntries([...$('#testParams').querySelectorAll('input,select')].map(x=>[x.name,x.value]));$('#testScript').textContent=String(test.command||'').replace(/\{([A-Za-z_][A-Za-z0-9_]*)\}/g,(m,k)=>values[k]??m)}
function renderSelectedTest(){const test=selectedTest();if(!test)return;$('#testDescription').textContent=test.description||'无测试说明';$('#testParams').innerHTML=(test.params||[]).map(p=>{const control=p.choices?`<select name="${esc(p.name)}">${p.choices.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}</select>`:`<input name="${esc(p.name)}" type="${p.type==='number'?'number':'text'}" value="${esc(p.default??'')}">`;return `<label>${esc(p.label||p.name)}${control}</label>`}).join('')||'<span class="no-params">此测试无需参数</span>';$('#testParams').querySelectorAll('input,select').forEach(x=>x.oninput=updateScriptPreview);updateScriptPreview()}
function renderTests(){if(!$('#testSelect'))return;const tests=config.tests||[],select=$('#testSelect'),empty=$('#noTests');select.innerHTML=tests.map(t=>`<option value="${esc(t.id)}">${esc(t.name)} (${esc(t.id)})</option>`).join('');const has=tests.length>0;$('.test-select-row').classList.toggle('hidden',!has);$('#testDescription').classList.toggle('hidden',!has);$('#testParams').classList.toggle('hidden',!has);$('.script-title').classList.toggle('hidden',!has);$('#testScript').classList.toggle('hidden',!has);empty.classList.toggle('hidden',has);if(has)renderSelectedTest()}
async function runTest(){const test=selectedTest();if(!test)return;try{const params=Object.fromEntries([...$('#testParams').querySelectorAll('input,select')].map(x=>[x.name,x.value]));const job=await api('/api/tests',{method:'POST',body:JSON.stringify({testId:test.id,params})});testJob=job.id;$('#testRun').classList.remove('hidden');$('#testOutput').textContent='';$('#runTitle').textContent=job.name;watchJob(job.id,'#testOutput',()=>testJob=null)}catch(e){toast(e.message)}}
async function loadPlatformScripts(){const state=$('#platformScriptState'),select=$('#platformScriptSelect'),run=$('#runPlatformScript');state.className='pytest-state';state.textContent='正在扫描当前平台 scripts/ 目录…';run.disabled=true;try{const result=await api('/api/platform-scripts');select.innerHTML=result.items.map(item=>`<option value="${esc(item.id)}">${esc(item.path)} [${item.type.toUpperCase()}]</option>`).join('');platformScriptsLoaded=true;run.disabled=!result.count;state.textContent=result.count?`已发现 ${result.count} 个脚本 · ${result.directory}`:`未发现脚本 · 请放入 ${result.directory}`;state.classList.toggle('good',result.count>0)}catch(e){select.innerHTML='';state.textContent=e.message;state.classList.add('bad')}}
async function runPlatformScript(){const scriptId=$('#platformScriptSelect').value;if(!scriptId)return;try{const job=await api('/api/platform-scripts/run',{method:'POST',body:JSON.stringify({scriptId})});testJob=job.id;$('#testRun').classList.remove('hidden');$('#testOutput').textContent='';$('#runTitle').textContent=job.name;watchJob(job.id,'#testOutput',()=>testJob=null)}catch(e){toast(e.message)}}
async function loadPytests(){const state=$('#pytestState'),select=$('#pytestSelect'),run=$('#runPytest');state.className='pytest-state';state.textContent='正在收集 test/ 目录中的用例…';run.disabled=true;try{const result=await api('/api/pytest/collect');select.innerHTML=result.items.map(id=>`<option value="${esc(id)}">${esc(id)}</option>`).join('');pytestLoaded=true;run.disabled=!result.count;state.textContent=result.count?`已发现 ${result.count} 个 Pytest 用例`:'test/ 目录中没有发现 Pytest 用例';state.classList.toggle('good',result.count>0)}catch(e){select.innerHTML='';state.textContent=e.message;state.classList.add('bad')}}
async function runPytest(){const nodeId=$('#pytestSelect').value;if(!nodeId)return;try{const job=await api('/api/pytest/run',{method:'POST',body:JSON.stringify({nodeId})});testJob=job.id;$('#testRun').classList.remove('hidden');$('#testOutput').textContent='';$('#runTitle').textContent=job.name;watchJob(job.id,'#testOutput',()=>testJob=null)}catch(e){toast(e.message)}}
function appendOutput(selector,lines){const out=$(selector);for(const l of lines){const span=document.createElement('span');span.className=l.stream;span.textContent=l.text+'\n';out.append(span)}out.scrollTop=out.scrollHeight}
function watchJob(id,selector,onDone=()=>{}){let cursor=0;const timer=setInterval(async()=>{try{const job=await api(`/api/jobs/${id}?after=${cursor}`);appendOutput(selector,job.lines);cursor=job.cursor;if(!['queued','running','stopping'].includes(job.status)){clearInterval(timer);appendOutput(selector,[{stream:job.exitCode===0?'stdout':'stderr',text:`[结束] exit=${job.exitCode} status=${job.status}`}]);onDone(job)}}catch(e){clearInterval(timer);onDone({status:'failed'})}},250)}
let lastTerminalSize='';
function syncTerminalSize(){if(!terminalConnected||!terminalSocket||terminalSocket.readyState!==WebSocket.OPEN)return;const key=`${xterm.cols}x${xterm.rows}`;if(key===lastTerminalSize)return;lastTerminalSize=key;terminalSocket.send(JSON.stringify({type:'resize',columns:xterm.cols,rows:xterm.rows}))}
function fitTerminal(){const page=$('#terminal');if(!page.classList.contains('active'))return;const top=page.getBoundingClientRect().top,available=Math.max(320,window.innerHeight-top-24);page.style.height=`${available}px`;requestAnimationFrame(()=>{terminalFitAddon.fit();syncTerminalSize()})}
function connectTerminal(){if(terminalSocket&&(terminalSocket.readyState===WebSocket.OPEN||terminalSocket.readyState===WebSocket.CONNECTING))return;$('#terminalStatus').textContent='连接中';$('#terminalReconnect').classList.add('hidden');const protocol=location.protocol==='https:'?'wss':'ws',accessToken=getAccessToken(),token=accessToken?`?token=${encodeURIComponent(accessToken)}`:'';terminalSocket=new WebSocket(`${protocol}://${location.host}/ws/terminal${token}`);terminalSocket.onopen=()=>{lastTerminalSize=''};terminalSocket.onmessage=e=>{const message=JSON.parse(e.data);if(message.type==='ready'){terminalConnected=true;$('#terminalStatus').textContent='已连接';$('#terminalBackend').textContent=(message.backend||'pty').toUpperCase();$('#terminalStop').classList.remove('hidden');terminalFitAddon.fit();syncTerminalSize();xterm.focus()}else if(message.type==='output')xterm.write(message.data);else if(message.type==='error')xterm.write(`\r\n\x1b[31m[终端错误] ${message.message}\x1b[0m\r\n`);else if(message.type==='exit')xterm.write(`\r\n\x1b[33m[会话结束] exit=${message.code}\x1b[0m\r\n`)};terminalSocket.onclose=()=>{terminalConnected=false;lastTerminalSize='';$('#terminalStatus').textContent='已断开';$('#terminalBackend').textContent='';$('#terminalStop').classList.add('hidden');$('#terminalReconnect').classList.remove('hidden');terminalSocket=null};terminalSocket.onerror=()=>xterm.write('\r\n\x1b[31m[WebSocket 连接失败]\x1b[0m\r\n')}
function terminalSend(data){if(!terminalConnected){connectTerminal();toast('终端正在连接');return false}terminalSocket.send(JSON.stringify({type:'input',data}));return true}
function resetTerminal(){if(terminalSocket)terminalSocket.close();terminalSocket=null;terminalConnected=false;sftpLoaded=false;$('#terminalStatus').textContent='已断开'}
function rememberCommand(command){command=command.trim();if(!command)return;terminalHistory=[command,...terminalHistory.filter(item=>item!==command)].slice(0,100);localStorage.setItem('cameraDebugTerminalHistory',JSON.stringify(terminalHistory));renderTerminalHistory()}
function trackTerminalInput(data){if(data.startsWith('\x1b['))return;for(const char of data){if(char==='\r'||char==='\n'){rememberCommand(terminalLineBuffer);terminalLineBuffer=''}else if(char==='\x7f'||char==='\b')terminalLineBuffer=terminalLineBuffer.slice(0,-1);else if(char>=' '&&char!=='\x1b')terminalLineBuffer+=char}}
function renderTerminalHistory(){$('#terminalHistory').innerHTML='<option value="">命令历史</option>'+terminalHistory.map(command=>`<option value="${esc(command)}">${esc(command)}</option>`).join('')}
function renderQuickCommands(){$('#quickCommands').innerHTML=quickCommands.map((item,index)=>`<button data-index="${index}" title="${esc(item.command)}">${esc(item.name)}</button>`).join('');$$('#quickCommands button').forEach(button=>button.onclick=()=>{const item=quickCommands[Number(button.dataset.index)];rememberCommand(item.command);terminalSend(item.command+'\r');xterm.focus()})}
xterm.onData(data=>{trackTerminalInput(data);terminalSend(data)});
xterm.onResize(syncTerminalSize);
xterm.onSelectionChange(()=>{const selection=xterm.getSelection();if(selection)navigator.clipboard?.writeText(selection).catch(()=>{})});
$('#terminalOutput').oncontextmenu=async event=>{event.preventDefault();try{const text=await navigator.clipboard.readText();if(text)terminalSend(text)}catch{toast('浏览器未允许读取剪贴板，请在地址栏授权剪贴板权限')}};
$('#terminalShell').onclick=e=>{if(!e.target.closest('button'))xterm.focus()};
if('ResizeObserver'in window){const terminalResizeObserver=new ResizeObserver(()=>{if($('#terminal').classList.contains('active')){terminalFitAddon.fit();syncTerminalSize()}});terminalResizeObserver.observe($('#terminalOutput'))}
window.addEventListener('resize',fitTerminal);window.visualViewport?.addEventListener('resize',fitTerminal);
window.addEventListener('beforeunload',()=>terminalSocket?.close());
const diagnostics=createDiagnostics({api,escapeHtml:esc,notify:toast});
const loadDiagnostics=diagnostics.load;
$('#clearTerminal').onclick=()=>xterm.clear();
$('#terminalReconnect').onclick=connectTerminal;
$('#terminalHistory').onchange=event=>{if(event.target.value){terminalSend(event.target.value);terminalLineBuffer=event.target.value;xterm.focus();event.target.value=''}};
$('#addQuickCommand').onclick=()=>{const command=prompt('快捷命令内容');if(!command?.trim())return;const name=prompt('显示名称',command.trim().slice(0,12));if(!name?.trim())return;quickCommands.push({name:name.trim(),command:command.trim()});localStorage.setItem('cameraDebugQuickCommands',JSON.stringify(quickCommands));renderQuickCommands()};
const searchOptions={incremental:true,decorations:{matchBackground:'#35506b',matchOverviewRuler:'#55a7ff',activeMatchBackground:'#d38b2c',activeMatchColorOverviewRuler:'#ffbd5a'}};
function searchTerminal(previous=false){const term=$('#terminalSearch').value;if(!term){terminalSearchAddon.clearDecorations();$('#terminalSearchResult').textContent='';return}previous?terminalSearchAddon.findPrevious(term,searchOptions):terminalSearchAddon.findNext(term,searchOptions)}
terminalSearchAddon.onDidChangeResults(result=>$('#terminalSearchResult').textContent=result.resultCount?`${result.resultIndex+1}/${result.resultCount}`:'0/0');
$('#terminalSearch').oninput=()=>searchTerminal(false);$('#terminalSearch').onkeydown=event=>{if(event.key==='Enter'){event.preventDefault();searchTerminal(event.shiftKey)}else if(event.key==='Escape'){event.target.value='';searchTerminal()}};
$('#terminalSearchPrev').onclick=()=>searchTerminal(true);$('#terminalSearchNext').onclick=()=>searchTerminal(false);
renderTerminalHistory();renderQuickCommands();
function formatFileSize(size){if(size<1024)return `${size} B`;if(size<1024*1024)return `${(size/1024).toFixed(1)} KB`;return `${(size/1024/1024).toFixed(1)} MB`}
async function loadSftp(path='/'){const files=$('#sftpFiles'),status=$('#sftpStatus');if(config.target?.transport!=='ssh'){files.innerHTML='<div class="sftp-empty">当前为 Local 模式，SFTP 仅对 SSH 目标可用</div>';status.textContent='';sftpLoaded=true;return}status.textContent='正在读取目录…';try{const result=await api(`/api/sftp/list?path=${encodeURIComponent(path)}`);sftpPath=result.path;$('#sftpPath').value=sftpPath;$('#sftpParent').disabled=sftpPath==='/';files.innerHTML=result.entries.length?result.entries.map((item,index)=>`<button class="sftp-entry ${item.type}" data-index="${index}" title="${esc(item.path)}"><b>${item.type==='directory'?'▸':'·'}</b><span>${esc(item.name)}</span><small>${item.type==='directory'?'目录':formatFileSize(item.size)}</small></button>`).join(''):'<div class="sftp-empty">目录为空</div>';$$('.sftp-entry.directory').forEach(button=>button.onclick=()=>loadSftp(result.entries[Number(button.dataset.index)].path));status.textContent=`${result.entries.length} 项`;sftpLoaded=true}catch(error){files.innerHTML=`<div class="sftp-empty">${esc(error.message)}</div>`;status.textContent='读取失败'}}
async function fileAsBase64(file){const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let index=0;index<bytes.length;index+=32768)binary+=String.fromCharCode(...bytes.subarray(index,index+32768));return btoa(binary)}
async function uploadSftpFiles(files){files=[...files];if(!files.length)return;if(config.target?.transport!=='ssh'){toast('SFTP 上传仅适用于 SSH 目标');return}for(let index=0;index<files.length;index++){const file=files[index];if(file.size>24*1024*1024){toast(`${file.name} 超过 24 MB，已跳过`);continue}$('#sftpStatus').textContent=`上传 ${index+1}/${files.length}：${file.name}`;try{await api('/api/sftp/upload',{method:'POST',body:JSON.stringify({path:sftpPath,name:file.name,content:await fileAsBase64(file)})})}catch(error){toast(`${file.name} 上传失败：${error.message}`);$('#sftpStatus').textContent='上传失败';return}}toast(`已上传 ${files.length} 个文件`);await loadSftp(sftpPath)}
$('#refreshSftp').onclick=()=>loadSftp(sftpPath);$('#sftpParent').onclick=()=>{const parent=sftpPath==='/'?'/':sftpPath.replace(/\/+[^/]+$/,'')||'/';loadSftp(parent)};$('#openSftpPath').onclick=()=>loadSftp($('#sftpPath').value);$('#sftpPath').onkeydown=event=>{if(event.key==='Enter')loadSftp(event.target.value)};
$('#toggleSftp').onclick=()=>{const panel=$('#sftpPanel'),collapsed=panel.classList.toggle('collapsed');$('#toggleSftp').textContent=collapsed?'›':'‹';setTimeout(fitTerminal,180)};
$('#sftpUpload').onchange=event=>{uploadSftpFiles(event.target.files);event.target.value=''};
for(const type of ['dragenter','dragover'])$('#sftpDrop').addEventListener(type,event=>{event.preventDefault();event.dataTransfer.dropEffect='copy';$('#sftpDrop').classList.add('dragging')});
for(const type of ['dragleave','drop'])$('#sftpDrop').addEventListener(type,event=>{$('#sftpDrop').classList.remove('dragging');if(type==='drop'){event.preventDefault();uploadSftpFiles(event.dataTransfer.files)}});
async function monitorAction(button,payload,message){if(button.disabled)return;button.disabled=true;try{const result=await api('/api/metrics/control',{method:'POST',body:JSON.stringify(payload)});toast(`${message}${result.scheduled!=null?`（${result.scheduled} 项）`:''}`);await updateMetrics()}catch(e){toast('监控操作失败：'+e.message)}finally{setTimeout(()=>button.disabled=false,500)}}
$('#toggleMonitoring').onclick=async()=>{const button=$('#toggleMonitoring'),paused=button.textContent.includes('恢复');await monitorAction(button,{action:paused?'resume':'pause'},paused?'监控已恢复':'监控已暂停')};
$('#refreshMetrics').onclick=()=>monitorAction($('#refreshMetrics'),{action:'refresh',group:$('#metricGroup').value||null},$('#metricGroup').value?'已刷新所选分组':'已刷新全部指标');
$('#retryMetrics').onclick=()=>monitorAction($('#retryMetrics'),{action:'refresh',group:$('#metricGroup').value||null,failedOnly:true},'已重试失败指标');
$('#metricGroup').onchange=()=>renderMetrics(Object.values(metricState));
if($('#testSelect')){$('#testSelect').onchange=renderSelectedTest;$('#runSelectedTest').onclick=runTest}
$('#refreshPlatformScripts').onclick=()=>{platformScriptsLoaded=false;loadPlatformScripts()};$('#runPlatformScript').onclick=runPlatformScript;
$('#refreshPytest').onclick=()=>{pytestLoaded=false;loadPytests()};$('#runPytest').onclick=runPytest;
$('#metricForm').elements.parserType.onchange=toggleParserFields;
$('#editMetrics').onclick=()=>setMetricEditing(true);
$('#newMetric').onclick=()=>{const metrics=metricList();let number=metrics.length+1,id=`metric_${number}`;while(metrics.some(item=>item.id===id))id=`metric_${++number}`;metrics.push({id,name:'New Metric',group:'GLOBAL',command:'echo 0',enabled:true,interval:2,timeout:5,parser:{type:'text'},display:{kind:'status'}});selectedMetricIndex=metrics.length-1;fillMetricForm()};
$('#saveMetric').onclick=()=>metricList().length?saveMetric():saveEmptyMetricList();
$('#cancelMetric').onclick=async()=>{try{await api('/api/config/reload',{method:'POST',body:'{}'});await load();setMetricEditing(false);toast('已放弃指标修改')}catch(e){toast('取消失败：'+e.message)}};
$('#reloadMetric').onclick=fillMetricForm;
$('#deleteMetric').onclick=()=>{const metrics=metricList(),metric=metrics[selectedMetricIndex];if(!metric||!confirm(`确定删除指标“${metric.name||metric.id}”吗？`))return;metrics.splice(selectedMetricIndex,1);for(const edge of config.topology?.edges||[]){if(edge.linkMetric===metric.id)delete edge.linkMetric;if(edge.videoMetric===metric.id)delete edge.videoMetric}selectedMetricIndex=Math.max(0,Math.min(selectedMetricIndex,metrics.length-1));fillMetricForm();renderMetrics();toast('指标已移除，点击“保存指标”后生效')};
$('#editTopology').onclick=()=>{topologyEditing=true;$('#topology').classList.add('editing');$('#topologyEditor').classList.remove('hidden');$('#editTopology').classList.add('hidden');refreshTopologyEditor();renderTopology()};
$('#editTopology').addEventListener('click',()=>setTopologyZoom(1));
$('#topologyZoomOut').onclick=()=>setTopologyZoom(topologyZoom-.1);
$('#topologyZoomReset').onclick=()=>setTopologyZoom(1);
$('#topologyZoomFit').onclick=fitTopology;
$('#topologyZoomIn').onclick=()=>setTopologyZoom(topologyZoom+.1);
$('#topology').addEventListener('wheel',event=>{if(!event.ctrlKey)return;event.preventDefault();setTopologyZoom(topologyZoom+(event.deltaY<0?.1:-.1))},{passive:false});
$('#topologyHeight').oninput=e=>{config.topology.height=Math.max(400,Math.min(1600,Number(e.target.value)||520));renderTopology()};
$('#autoTopologyHeight').onclick=()=>{const nodes=config.topology?.nodes||[],cameraCount=nodes.filter(node=>node.type==='camera').length,height=Math.max(520,Math.min(1600,Math.max(cameraCount,Math.ceil(nodes.length/2))*110+100));config.topology.height=height;renderTopology();toast(`画布高度已自动调整为 ${height}px`)};
$('#cancelTopology').onclick=async()=>{try{await api('/api/config/reload',{method:'POST',body:'{}'});topologyEditing=false;selectedTopologyNode=null;$('#topology').classList.remove('editing');$('#topologyEditor').classList.add('hidden');$('#editTopology').classList.remove('hidden');await load();toast('已放弃拓扑修改')}catch(e){toast(e.message)}};
$('#saveTopology').onclick=async()=>{try{await api('/api/config/save',{method:'POST',body:JSON.stringify({config})});topologyEditing=false;selectedTopologyNode=null;$('#topology').classList.remove('editing');$('#topologyEditor').classList.add('hidden');$('#editTopology').classList.remove('hidden');await load();toast('拓扑配置已保存')}catch(e){toast('保存失败：'+e.message)}};
$('#topologyNodeSelect').onchange=e=>{selectedTopologyNode=e.target.value;$('#edgeFrom').value=selectedTopologyNode;if($('#edgeTo').value===selectedTopologyNode)$('#edgeTo').value=(config.topology?.nodes||[]).find(node=>node.id!==selectedTopologyNode)?.id||'';refreshTopologyEditor();renderTopology()};
for(const id of ['topologyNodeLabel','topologyNodeSubtitle','topologyNodeType','topologyNodeX','topologyNodeY','topologyNodeWidth','topologyNodeHeight'])$('#'+id).oninput=updateTopologyNode;
$('#addTopologyNode').onclick=()=>{const topology=config.topology||(config.topology={nodes:[],edges:[]});let index=1,id='node1';while(topology.nodes.some(n=>n.id===id))id='node'+(++index);topology.nodes.push({id,type:'device',label:'New Node',x:50,y:50});selectedTopologyNode=id;refreshTopologyEditor();renderTopology()};
$('#deleteTopologyNode').onclick=()=>{const topology=config.topology,node=topologyNode();if(!topology||!node)return;topology.nodes=topology.nodes.filter(n=>n.id!==node.id);topology.edges=(topology.edges||[]).filter(e=>e.from!==node.id&&e.to!==node.id);selectedTopologyNode=topology.nodes[0]?.id||null;refreshTopologyEditor();renderTopology()};
$('#addTopologyEdge').onclick=()=>{const topology=config.topology||(config.topology={nodes:[],edges:[]}),from=$('#edgeFrom').value,to=$('#edgeTo').value,fromLabel=$('#edgeFrom').selectedOptions[0]?.textContent||from,toLabel=$('#edgeTo').selectedOptions[0]?.textContent||to;if(!from||!to||from===to){toast('请选择两个不同节点');return}if(topology.edges.some(e=>e.from===from&&e.to===to)){toast(`连接已存在：${fromLabel} → ${toLabel}`);return}const edge={from,to},link=$('#edgeLinkMetric').value,video=$('#edgeVideoMetric').value;if(link)edge.linkMetric=link;if(video)edge.videoMetric=video;topology.edges.push(edge);refreshTopologyEditor();renderTopology();toast(`已新增连接：${fromLabel} → ${toLabel}`)};
$('#terminalStop').onclick=()=>{if(terminalSend('\x03'))toast('已发送 Ctrl+C')};
$('#stopJob').onclick=async()=>{if(testJob)await api(`/api/jobs/${testJob}/stop`,{method:'POST',body:'{}'})};
$('#reloadConfig').onclick=()=>{if(configEditor.isDirty()&&!confirm('确定恢复到本次加载时的原始配置吗？未保存修改将丢失。'))return;configEditor.restore()};
$('#formatConfig').onclick=()=>{try{$('#configPreview').value=JSON.stringify(JSON.parse($('#configPreview').value),null,2);configEditor.refresh()}catch(e){toast('JSON 格式错误：'+e.message)}};
$('#saveConfig').onclick=()=>configEditor.previewSave(load);
$('#switchProfile').onclick=async()=>{try{const file=$('#profileSelect').value;if(!file||!configEditor.confirmDiscard('切换平台'))return;await api('/api/config/switch',{method:'POST',body:JSON.stringify({file})});resetTerminal();await load();toast('已切换平台配置')}catch(e){toast(e.message)}};
$('#copyProfile').onclick=async()=>{const sourceFile=$('#profileSelect').value;if(!sourceFile)return;if(!configEditor.confirmDiscard('复制并切换平台'))return;const sourceName=$('#profileSelect').selectedOptions[0]?.textContent?.split(' · ')[0]||'平台',name=prompt('新平台显示名称',sourceName+' 副本');if(!name)return;const suggested=name.trim().toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/^-|-$/g,'')||'profile-copy',file=prompt('新平台目录名（仅字母、数字、下划线和连字符）',suggested);if(!file)return;try{const result=await api('/api/config/profiles/copy',{method:'POST',body:JSON.stringify({sourceFile,file,name:name.trim()})});await api('/api/config/switch',{method:'POST',body:JSON.stringify({file:result.file||result.profile?.file||file})});resetTerminal();await load();toast(`已复制并切换到“${name.trim()}”`)}catch(error){configEditor.showErrors(error);toast('复制失败：'+error.message)}};
async function saveTarget(){const form=$('#sshForm'),data=Object.fromEntries(new FormData(form));await api('/api/config/target',{method:'POST',body:JSON.stringify(data)});resetTerminal();await load();return data}
$('#sshForm').onsubmit=async e=>{e.preventDefault();try{await saveTarget();toast(config.target.transport==='ssh'?'SSH 配置已保存，终端已切换到远程':'已切换为本机模式')}catch(err){toast(err.message)}};
$('#testConnection').onclick=async()=>{const result=$('#connectionResult');result.className='';result.textContent='正在保存配置…';try{const selected=$('#sshForm').elements.transport.value;if(selected!=='ssh'){result.className='bad';result.textContent='当前是 Local 本机模式';toast('请选择 SSH（远程开发板）');return}await saveTarget();result.textContent='正在连接远程开发板…';const job=await api('/api/connection/test',{method:'POST',body:'{}'});let cursor=0;const timer=setInterval(async()=>{try{const state=await api(`/api/jobs/${job.id}?after=${cursor}`);cursor=state.cursor;if(state.status!=='running'){clearInterval(timer);const ok=state.status==='success';result.className=ok?'good':'bad';result.textContent=ok?`✓ SSH 已连接，终端目标：${config.target.user||''}@${config.target.host}`:'✕ SSH 连接失败';if(!ok)toast(state.lines.map(x=>x.text).join(' ')||'SSH 连接失败')}}catch(e){clearInterval(timer);result.className='bad';result.textContent='✕ '+e.message}},250)}catch(e){result.className='bad';result.textContent='✕ '+e.message}};
async function load(){config=await api('/api/config');hideAccessToken();$('#targetName').textContent=config.project?.name||'未命名项目';$('#targetHost').textContent=config.target?.transport==='local'?'Local':`${config.target?.user||''}@${config.target?.host||'未配置'}`;$('#terminalTarget').textContent=$('#targetHost').textContent;const form=$('#sshForm'),target=config.target||{};for(const name of ['transport','host','port','user','identityFile','connectTimeout'])if(form.elements[name])form.elements[name].value=target[name]??(name==='port'?22:name==='connectTimeout'?8:'');form.elements.password.value='';form.elements.password.placeholder=target.passwordConfigured?'已配置密码；留空则保留':'留空则使用私钥认证';$('#configInfo').innerHTML=`<dt>配置文件</dt><dd>${esc(config.configPath)}</dd><dt>平台</dt><dd>${esc(config.project?.platform||'通用')}</dd><dt>传输层</dt><dd>${esc(config.target?.transport||'ssh')}</dd><dt>密码状态</dt><dd>${target.passwordConfigured?'已配置（内容已脱敏）':'未配置'}</dd><dt>监控指标</dt><dd>${config.monitoring?.metrics?.length||0} 项</dd><dt>测试任务</dt><dd>${config.tests?.length||0} 项</dd>`;const preview=JSON.parse(JSON.stringify(config));delete preview.configPath;if(preview.target)delete preview.target.passwordConfigured;configEditor.setOriginal(preview);const profileData=await api('/api/config/profiles');$('#profileSelect').innerHTML=profileData.profiles.map(p=>`<option value="${esc(p.file)}" ${p.active?'selected':''}>${esc(p.name)} · ${esc(p.platform)}</option>`).join('');renderMetrics();renderTests();selectedMetricIndex=Math.max(0,Math.min(selectedMetricIndex,metricList().length-1));fillMetricForm()}
initAuth({onAuthenticated:load,notify:toast});
setInterval(updateMetrics,1000);setInterval(()=>$('#clock').textContent=new Date().toLocaleString(),1000);load().catch(e=>toast(e.message));
